line-length = 120

[lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = ["D100", "D104", "D105", "D107"]

[lint.pydocstyle]
convention = "google"

[format]
docstring-code-format = true

[lint.per-file-ignores]
"tests/**" = ["D"]
"*_test.py" = ["D"]
"docs_src/**" = ["D"]
